name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ${SSH_USER}@${SERVER_IP} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python app.py &
          EOF
